[tool.poetry]
name = "Max"
version = "0.1.0"
description = "Messanger Max & Vk Education | Hackathon"
authors = ["Kirill <smookkii@yandex.ru>"]
readme = "README.md"
packages = [{include = "webapp"}]

[tool.poetry.dependencies]
python = "^3.12"

fastapi = {version = "0.104.1", python = ">=3.12,<4.0"}
uvicorn = {version = "0.24.0.post1", python = ">=3.12,<4.0"}
aiohappyeyeballs = {version = "2.6.1", python = ">=3.12,<4.0"}
aiohttp = {version = "3.13.2", python = ">=3.12,<4.0"}
aioredis = {version = "2.0.1", python = ">=3.12,<4.0"}
aiosignal = {version = "1.4.0", python = ">=3.12,<4.0"}
alembic = {version = "1.17.1", python = ">=3.12,<4.0"}
annotated-types = {version = "0.7.0", python = ">=3.12,<4.0"}
async-timeout = {version = "5.0.1", python = ">=3.12,<4.0"}
asyncmaxbot = {version = "1.4.3", python = ">=3.12,<4.0"}
asyncpg = {version = "0.30.0", python = ">=3.12,<4.0"}
attrs = {version = "25.4.0", python = ">=3.12,<4.0"}
frozenlist = {version = "1.8.0", python = ">=3.12,<4.0"}
idna = {version = "3.11", python = ">=3.12,<4.0"}
loguru = {version = "0.7.3", python = ">=3.12,<4.0"}
Mako = {version = "1.3.10", python = ">=3.12,<4.0"}
MarkupSafe = {version = "3.0.3", python = ">=3.12,<4.0"}
multidict = {version = "6.7.0", python = ">=3.12,<4.0"}
propcache = {version = "0.4.1", python = ">=3.12,<4.0"}
pydantic = {version = "2.12.4", python = ">=3.12,<4.0"}
pydantic-core = {version = "2.41.5", python = ">=3.12,<4.0"}
redis = {version = "7.0.1", python = ">=3.12,<4.0"}
SQLAlchemy = {version = "2.0.44", python = ">=3.12,<4.0"}
typing-inspection = {version = "0.4.2", python = ">=3.12,<4.0"}
typing_extensions = {version = "4.15.0", python = ">=3.12,<4.0"}
yarl = {version = "1.22.0", python = ">=3.12,<4.0"}
python-dotenv = {version = "1.0.0", python = ">=3.12,<4.0"}

# Платформозависимые пакеты
greenlet = {version = "3.2.4", python = ">=3.12,<4.0", markers = 'platform_machine == "aarch64" or platform_machine == "ppc64le" or platform_machine == "x86_64" or platform_machine == "amd64" or sys_platform == "win32"'}
colorama = {version = "0.4.6", python = ">=3.12,<4.0", markers = 'platform_system == "Windows" or sys_platform == "win32"'}
win32-setctime = {version = "1.2.0", python = ">=3.12,<4.0", markers = 'sys_platform == "win32"'}

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-asyncio = "^0.21.0"
black = "^23.0.0"
isort = "^5.12.0"
mypy = "^1.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
